micronaut:
  application:
    name: inventory-service
grpc:
  server:
    port: 9091
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
datasources:
  default:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5434/inventory}
    username: ${JDBC_USER:ecom}
    password: ${JDBC_PASSWORD:ecom}
